[package]
name = "sma_exporter"
version = "0.1.0"
authors = ["dr0ps https://github.com/dr0ps"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus = {version="0.9.0", features = ["gen"]}
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
byteorder = "1.3.4"
lazy_static = "1.4.0"
socket2 = {version = "0.3.16", features = ["reuseport"]}

arc-swap = "0.4.8"
futures-task ="0.3.7"
futures-util = "0.3.7"